title: Find Untagged Tumblr Posts
author: "Alex Chan"
url: "https://finduntaggedtumblrposts.com/"

source: "src"
destination: "_site"

sass:
  sass_dir: _scss
  style: compressed

liquid:
  error_mode: strict
