[build]
  publish = "site/"

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true

[[headers]]
  for = "/theme"

  [headers.values]
		cache-control = "public, max-age=31536000"
