[build]
  base = ""
  publish = "site/"

[[headers]]
  for = "/theme/*"

  [headers.values]
		cache-control = "public, max-age=31536000"

# I test my security headers with https://securityheaders.com/
#
# This config is based on the config for my main site, see
# https://github.com/alexwlchan/alexwlchan.net/blob/live/netlify.toml
[[headers]]
  for = "/*"

  [headers.values]
    # https://scotthelme.co.uk/hardening-your-http-response-headers/#content-security-policy
    content-security-policy = """\
    default-src 'self'; \
    connect-src https://api.tumblr.com; \
    script-src 'self' 'unsafe-inline' https://code.jquery.com; \
    style-src 'self' 'unsafe-inline';\
    """

    # https://scotthelme.co.uk/a-new-security-header-feature-policy/
    # https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/
    permissions-policy = """\
      geolocation=(), \
      midi=(), \
      notifications=(), \
      push=(), \
      sync-xhr=(), \
      microphone=(), \
      camera=(), \
      magnetometer=(), \
      gyroscope=(), \
      vibrate=(),
      payment=() \
    """

    # https://scotthelme.co.uk/a-new-security-header-referrer-policy/
    referrer-policy = "no-referrer-when-downgrade"

    # https://scotthelme.co.uk/hardening-your-http-response-headers/#strict-transport-security
    strict-transport-security = "max-age=31536000; includeSubDomains"

    # https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options
    x-content-type-options = "nosniff"

    # https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options
    x-frame-options = "DENY"

    # https://scotthelme.co.uk/hardening-your-http-response-headers/#x-xss-protection
    x-xss-protection = "1; mode=block"
